import {
    FiServer,
    FiCheckCircle,
    FiXCircle,
    FiBox,
    FiAlertTriangle,
    FiCpu,
    FiActivity,
    FiSlash,
} from "react-icons/fi";

export const getDashboardCards = (summary, navigate) => [
    {
        title: "Total Devices",
        value: summary.totalDevices,
        subtitle: "Registered devices",
        icon: FiServer,
        iconBg: "bg-blue-100",
        iconColor: "text-blue-600",
        onClick: () => navigate("/devices"),
    },
    {
        title: "Online Devices",
        value: summary.onlineDevices,
        subtitle: "Currently reachable",
        icon: FiCheckCircle,
        iconBg: "bg-green-100",
        iconColor: "text-green-600",
        onClick: () => navigate("/devices?status=ONLINE"),
    },
    {
        title: "Offline Devices",
        value: summary.offlineDevices,
        subtitle: "Need attention",
        icon: FiXCircle,
        iconBg: "bg-red-100",
        iconColor: "text-red-600",
        onClick: () => navigate("/devices?status=OFFLINE"),
    },
    {
        title: "Monitoring Enabled",
        value: summary.monitoringEnabled,
        subtitle: "Active monitoring",
        icon: FiActivity,
        iconBg: "bg-purple-100",
        iconColor: "text-purple-600",
        onClick: () => navigate("/devices?monitoring=enabled"),
    },
    {
        title: "Monitoring Disabled",
        value: summary.monitoringDisabled,
        subtitle: "Monitoring turned off",
        icon: FiSlash,
        iconBg: "bg-yellow-100",
        iconColor: "text-yellow-600",
        onClick: () => navigate("/devices?monitoring=disabled"),
    },
    {
        title: "Critical Devices",
        value: summary.criticalDevices ?? summary.criticalAlerts ?? 0,
        subtitle: "Require immediate attention",
        icon: FiAlertTriangle,
        iconBg: "bg-red-100",
        iconColor: "text-red-600",
        onClick: () => navigate("/devices?critical=true"),
    },
    /*
    {
        title: "Critical Devices",
        value: summary.criticalDevices,
        subtitle: "Require immediate attention",
        icon: FiAlertTriangle,
        iconBg: "bg-red-100",
        iconColor: "text-red-600",
        onClick: () => navigate("/devices?status=CRITICAL"),
    },
    */
];
